String API_KEY =
    "ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmpiR0Z6Y3lJNklrMWxjbU5vWVc1MElpd2ljSEp2Wm1sc1pWOXdheUk2TnpNNU56RTNMQ0p1WVcxbElqb2lhVzVwZEdsaGJDSjkubnpuZGFCWWN4NGtnV0kxZkg1ZkdnLVBaVDFVTTRyVUhxQjkzaTNCNHdxTmhXQUVlLXVuTnhBblFVVEQtMzQ3Q091RnhiQWUzaWJDQlZrT2xqbGt1OXc=";

String AUTH_TOKEN = "";
String ORDER_ID = "";

double INTEGRATION_CARD_ID = 3721507;

double INTEGRATION_KIOSK_ID = 3727458;

String REQUEST_TOKEN_CARD = "";
String REQUEST_TOKEN_KIOSK = "";
